### ISSUE TITLE
Move Grafana admin creds to secret

### ISSUE THREAD

**Issue by HumairAK** [AICoE/internal-data-hub#14]
This will require grafana operator 3.6, which as of this writing is not available in olm.  

Once we have moved to grafana operator 3.6, we will be able to add admin secrets as secrets. 

Currently grafana admin secrets are added directly from the grafana custom reasourse manifest. In operator 3.6, you can add them via [envFrom](https://github.com/integr8ly/grafana-operator/blob/v3.6.0/documentation/env_vars.md), allowing us to encrypt only the secret and not the entire grafana CR.

**Comment by anishasthana** [comment]
This was closed by #17
